version: '2'
services:
  db:
    image: mysql:8.0
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    # cap_add:
    #   - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Instabug_App_Chat
      MYSQL_USER: instabug
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      
  app:
    build: .
    command: bash -c "bundle exec rake db:migrate RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: Instabug_App_Chat
      DB_PASSWORD: password
      DB_HOST: db
    # volumes:
      # - db:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#volumes:
  #db:
    #driver: local
